from .iyunya_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .qwen_vl_ocr_node import NODE_CLASS_MAPPINGS as OCR_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as OCR_NODE_DISPLAY_NAME_MAPPINGS

# 合并节点映射
NODE_CLASS_MAPPINGS.update(OCR_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(OCR_NODE_DISPLAY_NAME_MAPPINGS)

# 定义web前端文件的位置 - 确保使用标准格式
WEB_DIRECTORY = "web"


__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
